[package]
name = "little-idp"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
url = "2"
bytes = "1" 
lazy_static = "1.4"
bcrypt = "0.17"
rand = "0.8"
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.22.1"